### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by lhs21** [hasanirtiza/Pedestron#100]
when I try to run /tools/demo.py , I got the output like this, but the image in result_demo is same as the image in demo. 
 There are not bounding boxes

demo/
['demo/3.png', 'demo/1.png', 'demo/2.png']
The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.layer2.0.conv1.weight, backbone.layer2.0.bn1.weight, backbone.layer2.0.bn1.bias, backbone.layer2.0.bn1.running_mean, backbone.layer2.0.bn1.running_var, backbone.layer2.0.bn1.num_batches_tracked, backbone.layer2.0.conv2.weight, backbone.layer2.0.bn2.weight, backbone.layer2.0.bn2.bias, backbone.layer2.0.bn2.running_mean, backbone.layer2.0.bn2.running_var, backbone.layer2.0.bn2.num_batches_tracked, backbone.layer2.0.conv3.weight, backbone.layer2.0.bn3.weight, backbone.layer2.0.bn3.bias, backbone.layer2.0.bn3.running_mean, backbone.layer2.0.bn3.running_var, backbone.layer2.0.bn3.num_batches_tracked, backbone.layer2.0.downsample.0.weight, backbone.layer2.0.downsample.1.weight, backbone.layer2.0.downsample.1.bias, backbone.layer2.0.downsample.1.running_mean, backbone.layer2.0.downsample.1.running_var, backbone.layer2.0.downsample.1.num_batches_tracked, backbone.layer2.1.conv1.weight, backbone.layer2.1.bn1.weight, backbone.layer2.1.bn1.bias, backbone.layer2.1.bn1.running_mean, backbone.layer2.1.bn1.running_var, backbone.layer2.1.bn1.num_batches_tracked, backbone.layer2.1.conv2.weight, backbone.layer2.1.bn2.weight, 

.........
these keys have mismatched shape:
.......
/data/shans/eval/Pedestron-master/tools/../mmdet/apis/inference.py:39: UserWarning: Clas       s names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3/3, 2.2 task/s, elapsed: 1s, ETA:     0s(pytor       ch1.1)

type:
python tools/demo.py configs/elephant/cityperson/csp_r50_hw.py ./models_pretrained/epoch_72.pth.stu demo/ result_demo/

my Environment
 - OS: [ Ubuntu 14.04.5]
 - GCC [4.9.4]
 - PyTorch version [1.1.0]
- How you installed PyTorch [conda]
- CUDA 9.0

**Comment by hasanirtiza** [comment]
Could you try `configs/elephant/cityperson/csp_r50.py` config instead.

**Comment by lhs21** [comment]
> Could you try `configs/elephant/cityperson/csp_r50.py` config instead.

I tried，but the result is the same.

**Comment by hasanirtiza** [comment]
The link was not pointing to the correct model, it is fixed, download the model and it should be fine.

**Comment by johnny12150** [comment]
Still facing the same issue now.
Code is [here](https://gist.github.com/johnny12150/d6b3a3edb9f9e51d75e2784689d0a322).
Some of the links in `readme.md` are also failed.
